### ISSUE TITLE
Item types not accurate

### ISSUE THREAD

**Issue by Forusim** [shamrickus/d2runewords#2]
Very good App.
However the item type for Spirit is only "Swords" and not "Weapons" in general.

![grafik](https://user-images.githubusercontent.com/176811/54793489-f5fc0e80-4c42-11e9-9819-5a5979401aa7.png)

**Comment by shamrickus** [comment]
Nice find, I'll push a fix asap.

**Comment by shamrickus** [comment]
Fixed in 7f667f7c0fb9d08443639121bfaf9f60d49f820d

Thanks again for the report.
