### ISSUE TITLE
Weapon Filter

### ISSUE THREAD

**Issue by ghost** [shamrickus/d2runewords#3]
Would it be possible to fix the way the filter works for selecting various weapons. Rather than just filtering weapon type, "melee weapons", "weapons" which work fine on their own, would it be possible to class options so that choosing swords specifically would show all sword runewords, including all melee weapon and all weapon runewords options. Trying to do this in reverse such as picking "sword" you either miss out on the "all weapons" option or end up including "missle weapons"

**Comment by shamrickus** [comment]
Yes it would, I'll look into getting this done; hopefully this weekend.

**Comment by ghost** [comment]
Appreciate that a ton! I've been using your site for 3 years+ and have been recommending it to everyone. Thanks for the effort you put into it! (I also show it on stream daily)

**Comment by shamrickus** [comment]
It has been implemented (as of version 1.5.0). 

As an example of how it works if you select "Maces", "Weapons" and "Melee Weapons" will also be selected. These can be deselected without issue. 

The type hierarchy is determined based on the d2 source files so theoretically it should be correct, let me know if you run into any issues.
